Implement new sign in screen
futureware-tech/delern pull request #1398
Opened 2020-05-16 11:35 UTC by ksheremet

Fixes #1394

2020-05-16 11:35 UTC, ksheremet commented
![Screenshot_1589562016](https://user-images.githubusercontent.com/6387464/82118863-24f40e80-977a-11ea-80ec-040aa3a9c6bc.png)

2020-09-03 07:15 UTC, ksheremet commented
![flutter_01](https://user-images.githubusercontent.com/6387464/92083263-0f0c6700-edc6-11ea-9670-03b7cd2ebeb8.png)

2020-09-08 11:44 UTC, dotdoom requested changes
1. Looks like the Facebook image now looks differently from what they provide on their website?
1. Please doublecheck that Facebook logo still displays, and correctly, in the navigation drawer when signed in with Facebook.

2020-09-08 11:44 UTC, dotdoom commented on flutter/lib/views/helpers/styles.dart
> +const kFacebookBlueColor = Color(0xFF4267B2);
Why not keep the comment?

2020-09-08 11:44 UTC, dotdoom commented on flutter/lib/views/sign_in/sign_in_button.dart
> +            //elevation: _buttonElevation,
If these are no longer necessary, please remove.

2020-09-08 11:44 UTC, dotdoom commented on flutter/lib/views/sign_in/sign_in_button.dart
> +Future<void> signInWithProvider({
What's the difference with _signInWithProvider method below?

2020-09-08 11:44 UTC, dotdoom commented on flutter/lib/views/sign_in/sign_in_button.dart
> +Future<void> signInWithProvider({
Since this method is no longer called from buttons, perhaps we could also move it outside of this file.  E.g. sign_in.dart where it's actually used?

2020-09-08 11:44 UTC, dotdoom commented on flutter/lib/views/sign_in/sign_in_button.dart
> +class FacebookSignInButton extends StatelessWidget {
I haven't checked but please confirm with Facebook (and perhaps Google?) guidelines that these sign in buttons are still displayed as they require.

2020-09-09 07:29 UTC, ksheremet commented
> 1. Looks like the Facebook image now looks differently from what they provide on their website?
> 2. Please doublecheck that Facebook logo still displays, and correctly, in the navigation drawer when signed in with Facebook.

For Facebook button it is a suggestion

2020-09-09 09:54 UTC, dotdoom approved these changes

2020-09-09 10:42 UTC, merged